In [3]:
import numpy as np

## Datatypes and Attributes

In [24]:
# Numpy's main datatype is ndarray

#Anatomy of Numpy Array

#Array, Vector    shape = (1,3)
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [3]:
type(a1)

numpy.ndarray

In [25]:
# Array, Matrix 2-D    shape = (2,3)
a2 = np.array([[1,2,3],[2,3,4],[4.1,2.1,3.1]])

#  Array, matrix        shape = (2,3,3)
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
              [[10,11,12],
               [13,14,15],
               [16,17,18]]])

In [6]:
a2

array([[1. , 2. , 3. ],
       [2. , 3. , 4. ],
       [4.1, 2.1, 3.1]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
# Shape
a1.shape

(5,)

In [11]:
a2.shape

(3, 3)

In [12]:
a3.shape

(2, 3, 3)

In [13]:
# Dimensions
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
# Datatypes
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [15]:
# Size
a1.size, a2.size, a3.size

(5, 9, 18)

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [18]:
# Create a DataFrame from a Numpy Array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  2.0  3.0  4.0
2  4.1  2.1  3.1

## Creating arrays

In [4]:
sample_array = np.array([1,2,3])
sample_array.dtype

dtype('int64')

In [6]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
zeros = np.zeros((2,2))
zeros

array([[0., 0.],
       [0., 0.]])

In [8]:
range_array = np.arange(0,6,1)
range_array

array([0, 1, 2, 3, 4, 5])

In [9]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[6, 2, 1, 8, 9],
       [9, 7, 4, 5, 8],
       [4, 6, 7, 9, 6]])

In [11]:
random_array2 = np.random.random((5,3))
random_array2

array([[0.03117658, 0.38476447, 0.01224818],
       [0.34839526, 0.80459453, 0.75660121],
       [0.21964191, 0.17720803, 0.04315261],
       [0.5341855 , 0.78838197, 0.87309959],
       [0.81885155, 0.05587422, 0.11287163]])

In [13]:
random_array2.shape

(5, 3)

In [14]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.72594295, 0.10359795, 0.33949237],
       [0.57996331, 0.40061533, 0.29769697],
       [0.09392655, 0.76554509, 0.97341785],
       [0.9161258 , 0.48694814, 0.05257039],
       [0.15011441, 0.27766015, 0.79020212]])

In [18]:
np.random.randint(1,3, size=(2,3))

array([[1, 1, 2],
       [2, 1, 1]])

In [21]:
# Pseudo Random numbers
np.random.seed(seed=1)
random_array4 = np.random.randint(10, size=(5,3))
random_array4

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]])

# Viewing arrays and matrices

In [22]:
np.unique(random_array4)

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [28]:
a1[0], a2[2][0]

(1, 4.1)

In [29]:
a3[0][1][2]

6

In [31]:
a3[::-3]

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [32]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[2, 4, 7, 7, 9],
         [1, 7, 0, 6, 9],
         [9, 7, 6, 9, 1],
         [0, 1, 8, 8, 3]],

        [[9, 8, 7, 3, 6],
         [5, 1, 9, 3, 4],
         [8, 1, 4, 0, 3],
         [9, 2, 0, 4, 9]],

        [[2, 7, 7, 9, 8],
         [6, 9, 3, 7, 7],
         [4, 5, 9, 3, 6],
         [8, 0, 2, 7, 7]]],


       [[[9, 7, 3, 0, 8],
         [7, 7, 1, 1, 3],
         [0, 8, 6, 4, 5],
         [6, 2, 5, 7, 8]],

        [[4, 4, 7, 7, 4],
         [9, 0, 2, 0, 7],
         [1, 7, 9, 8, 4],
         [0, 1, 9, 8, 2]],

        [[3, 1, 2, 7, 2],
         [6, 0, 9, 2, 6],
         [6, 2, 7, 7, 0],
         [6, 5, 1, 4, 6]]]])

In [33]:
a4[::3, ::4]

array([[[[2, 4, 7, 7, 9],
         [1, 7, 0, 6, 9],
         [9, 7, 6, 9, 1],
         [0, 1, 8, 8, 3]]]])

In [34]:
# Get first 4 numbers of inner most array
a4[:, :, :, :4]

array([[[[2, 4, 7, 7],
         [1, 7, 0, 6],
         [9, 7, 6, 9],
         [0, 1, 8, 8]],

        [[9, 8, 7, 3],
         [5, 1, 9, 3],
         [8, 1, 4, 0],
         [9, 2, 0, 4]],

        [[2, 7, 7, 9],
         [6, 9, 3, 7],
         [4, 5, 9, 3],
         [8, 0, 2, 7]]],


       [[[9, 7, 3, 0],
         [7, 7, 1, 1],
         [0, 8, 6, 4],
         [6, 2, 5, 7]],

        [[4, 4, 7, 7],
         [9, 0, 2, 0],
         [1, 7, 9, 8],
         [0, 1, 9, 8]],

        [[3, 1, 2, 7],
         [6, 0, 9, 2],
         [6, 2, 7, 7],
         [6, 5, 1, 4]]]])

## Manipulating & Comparing Arrays

### Arithmetic

In [46]:
a1 = np.arange(1,4,1)
a1

array([1, 2, 3])

In [38]:
ones = np.ones(5)

In [39]:
a1+ones

array([2., 3., 4., 5., 6.])

In [40]:
a1- ones

array([0., 1., 2., 3., 4.])

In [41]:
a1 * ones

array([1., 2., 3., 4., 5.])

In [44]:
a2  = np.random.randint(10, size =(2,3))
a2

array([[0, 6, 5],
       [1, 2, 1]])

In [47]:
a1 * a2

array([[ 0, 12, 15],
       [ 1,  4,  3]])

In [50]:
ones = np.ones(3)

In [51]:
a1 / ones

array([1., 2., 3.])

In [54]:
np.square(a2)

array([[ 0, 36, 25],
       [ 1,  4,  1]])

In [55]:
np.add(a1,a2)

array([[1, 8, 8],
       [2, 4, 4]])

In [56]:
a2 % 3

array([[0, 0, 2],
       [1, 2, 1]])

In [57]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [58]:
np.log10(a1)

array([0.        , 0.30103   , 0.47712125])

# Aggregation
performing same operation on a number of things

In [59]:
a1.sum()

6

In [60]:
sum(a1)

6

In [61]:
np.sum(a1)

6

## use py methods on py datatype
## use numpy's methods on numpy datatype

In [62]:
# Create a massive numpy array
massive_array = np.random.random(100000)
massive_array[:10]

array([0.76459257, 0.46739268, 0.26900105, 0.83169259, 0.55132494,
       0.0700815 , 0.47247504, 0.74276483, 0.19195608, 0.4643115 ])

In [64]:
%timeit sum(massive_array)   # python sum()
%timeit np.sum(massive_array)  # numpy sum()

15.8 ms ± 1.64 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
31.2 µs ± 116 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [65]:
a2

array([[0, 6, 5],
       [1, 2, 1]])

In [66]:
np.mean(a2)

2.5

In [67]:
np.max(a2)

6

In [68]:
#Standard Deviations is measure of  how spread out a group of numbers is from the mean
np.std(a2)

2.217355782608345

In [70]:
# Variance = measure of average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance  = lower range of numbers
np.var(a2)

4.916666666666667

In [71]:
# sd = sqrt of variance
np.sqrt(np.var(a2))

2.217355782608345